// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ActionID   string
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Outbox struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	Status        int16
	OccurredAt    pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	ErrorMessage  pgtype.Text
	RetryCount    int32
	RequestID     pgtype.UUID
}

type Permission struct {
	PermID      pgtype.UUID
	ResourceID  string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsRoot      bool
}

type PermissionAction struct {
	PaID     pgtype.UUID
	PermID   pgtype.UUID
	ActionID string
	AssignAt pgtype.Timestamptz
}

type Resource struct {
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Role struct {
	RoleID      pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	IsRoot      bool
	IsActive    bool
}

type RolePermission struct {
	RpID     pgtype.UUID
	RoleID   pgtype.UUID
	PermID   pgtype.UUID
	AssignAt pgtype.Timestamptz
}

type User struct {
	UserID         pgtype.UUID
	Email          string
	PasswordHash   string
	LockEnd        pgtype.Timestamptz
	LockReason     pgtype.Text
	LastLoginAt    pgtype.Timestamptz
	FailedAttempts pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserRole struct {
	UrID     pgtype.UUID
	UserID   pgtype.UUID
	RoleID   pgtype.UUID
	AssignAt pgtype.Timestamptz
}
