// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    request_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, occurred_at
`

type InsertOutboxParams struct {
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	RequestID     string
}

type InsertOutboxRow struct {
	ID         pgtype.UUID
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (InsertOutboxRow, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.RequestID,
	)
	var i InsertOutboxRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const insertOutboxBulk = `-- name: InsertOutboxBulk :exec
INSERT INTO outbox (
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    request_id
)
SELECT 
    unnest($1::text[])   AS aggregate_type,
    unnest($2::text[])   AS aggregate_id,
    unnest($3::text[])   AS event_type,
    unnest($4::jsonb[])  AS payload,
    unnest($5::text[])   AS request_id
`

type InsertOutboxBulkParams struct {
	Column1 []string
	Column2 []string
	Column3 []string
	Column4 [][]byte
	Column5 []string
}

func (q *Queries) InsertOutboxBulk(ctx context.Context, arg InsertOutboxBulkParams) error {
	_, err := q.db.Exec(ctx, insertOutboxBulk,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}
