// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: empty.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserById = `-- name: GetUserById :one
SELECT user_id, create_at, update_at FROM users WHERE user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, userID)
	var i User
	err := row.Scan(&i.UserID, &i.CreateAt, &i.UpdateAt)
	return i, err
}
