// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	PermID      pgtype.UUID
	Name        string
	Action      string
	Resource    string
	Description pgtype.Text
	CreateAt    pgtype.Timestamp
	UpdateAt    pgtype.Timestamp
}

type Role struct {
	RoleID      pgtype.UUID
	Name        string
	Description pgtype.Text
	CreateAt    pgtype.Timestamp
	UpdateAt    pgtype.Timestamp
}

type RolePermission struct {
	RpID     pgtype.UUID
	RoleID   pgtype.UUID
	PermID   pgtype.UUID
	AssignAt pgtype.Timestamp
}

type User struct {
	UserID   pgtype.UUID
	CreateAt pgtype.Timestamp
	UpdateAt pgtype.Timestamp
}

type UserRole struct {
	UrID     pgtype.UUID
	UserID   pgtype.UUID
	RoleID   pgtype.UUID
	AssignAt pgtype.Timestamp
}
