// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ActionID   string
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Permission struct {
	PermID      pgtype.UUID
	ResourceID  string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	IsRoot      bool
}

type PermissionAction struct {
	PaID     pgtype.UUID
	PermID   pgtype.UUID
	ActionID string
	AssignAt pgtype.Timestamp
}

type Resource struct {
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Role struct {
	RoleID      pgtype.UUID
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	IsRoot      bool
}

type RolePermission struct {
	RpID     pgtype.UUID
	RoleID   pgtype.UUID
	PermID   pgtype.UUID
	AssignAt pgtype.Timestamp
}

type User struct {
	UserID         pgtype.UUID
	Email          string
	PasswordHash   string
	LockEnd        pgtype.Timestamp
	LockReason     pgtype.Text
	LastLoginAt    pgtype.Timestamp
	FailedAttempts pgtype.Int4
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type UserRole struct {
	UrID     pgtype.UUID
	UserID   pgtype.UUID
	RoleID   pgtype.UUID
	AssignAt pgtype.Timestamp
}
