// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"auth_service/internal/controller"
	"auth_service/internal/mapper"
	"auth_service/internal/repos"
	"auth_service/internal/services"
)

// Injectors from auth.wire.go:

func InjectAuthWire() *controller.AuthController {
	authRepo := repos.NewAuthRepo()
	authService := services.NewAuthService(authRepo)
	authController := controller.NewAuthController(authService)
	return authController
}

func InjectPermissionWire() *controller.PermissionController {
	permissionRepo := repos.NewPermissionRepo()
	permissionMapper := mapper.NewPermissionMapper()
	permissionService := services.NewPermissionService(permissionRepo, permissionMapper)
	permissionController := controller.NewPermissionController(permissionService)
	return permissionController
}

func InjectRoleWire() *controller.RoleController {
	roleRepo := repos.NewRoleRepo()
	roleService := services.NewRoleService(roleRepo)
	roleController := controller.NewRoleController(roleService)
	return roleController
}

func InjectTokenWire() *controller.TokenController {
	tokenRepo := repos.NewTokenRepo()
	tokenService := services.NewTokenService(tokenRepo)
	tokenController := controller.NewTokenController(tokenService)
	return tokenController
}
