// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"auth_service/internal/controller"
	"auth_service/internal/repos"
	"auth_service/internal/services"
)

// Injectors from auth.wire.go:

func InjectAuthWire() *controller.AuthController {
	iAuthRepo := repos.NewAuthRepo()
	iAuthService := services.NewAuthService(iAuthRepo)
	authController := controller.NewAuthController(iAuthService)
	return authController
}

// Injectors from permission.wire.go:

func InjectPermissionWire() *controller.PermissionController {
	iPermissionRepo := repos.NewPermissionRepo()
	iPermissionService := services.NewPermissionService(iPermissionRepo)
	permissionController := controller.NewPermissionController(iPermissionService)
	return permissionController
}

// Injectors from role.wire.go:

func InjectRoleWire() *controller.RoleController {
	iRoleRepo := repos.NewRoleRepo()
	iRoleService := services.NewRoleService(iRoleRepo)
	roleController := controller.NewRoleController(iRoleService)
	return roleController
}

// Injectors from token.wire.go:

func InjectTokenWire() *controller.TokenController {
	iTokenRepo := repos.NewTokenRepo()
	iTokenService := services.NewTokenService(iTokenRepo)
	tokenController := controller.NewTokenController(iTokenService)
	return tokenController
}
